"""initial_schema

Revision ID: bbba007ba5f7
Revises: 
Create Date: 2026-08-21 09:51:35.268931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbba007ba5f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.alter_column('boosters', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('boosters', 'binance',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('boosters', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'1234'::text"))
    op.alter_column('boosters', 'discord_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_constraint(op.f('boosters_nombre_key'), 'boosters', type_='unique')
    op.create_index(op.f('ix_boosters_id'), 'boosters', ['id'], unique=False)
    op.create_index(op.f('ix_boosters_nombre'), 'boosters', ['nombre'], unique=True)
    op.alter_column('config_precios', 'precio_cliente',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('config_precios', 'margen_perez',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_config_precios_division'), 'config_precios', ['division'], unique=False)
    op.alter_column('inventario', 'user_pass',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('inventario', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_inventario_id'), 'inventario', ['id'], unique=False)
    op.create_index(op.f('ix_inventario_user_pass'), 'inventario', ['user_pass'], unique=True)
    op.alter_column('pedidos', 'opgg',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('pedidos', 'notas',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'FRESH'::text"))
    op.create_index(op.f('ix_pedidos_booster_nombre'), 'pedidos', ['booster_nombre'], unique=False)
    op.create_index(op.f('ix_pedidos_estado'), 'pedidos', ['estado'], unique=False)
    op.create_index(op.f('ix_pedidos_fecha_fin_real'), 'pedidos', ['fecha_fin_real'], unique=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_pago_realizado'), 'pedidos', ['pago_realizado'], unique=False)
    op.create_foreign_key(None, 'pedidos', 'boosters', ['booster_id'], ['id'])
    op.alter_column('sistema_config', 'valor',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_sistema_config_clave'), 'sistema_config', ['clave'], unique=False)
    op.alter_column('wallet_perez', 'fecha',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('wallet_perez', 'tipo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('wallet_perez', 'categoria',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('wallet_perez', 'monto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('wallet_perez', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_wallet_perez_id'), 'wallet_perez', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_perez_id'), table_name='wallet_perez')
    op.alter_column('wallet_perez', 'descripcion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('wallet_perez', 'monto',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('wallet_perez', 'categoria',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('wallet_perez', 'tipo',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('wallet_perez', 'fecha',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_sistema_config_clave'), table_name='sistema_config')
    op.alter_column('sistema_config', 'valor',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_index(op.f('ix_pedidos_pago_realizado'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_fecha_fin_real'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_estado'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_booster_nombre'), table_name='pedidos')
    op.alter_column('pedidos', 'notas',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'FRESH'::text"))
    op.alter_column('pedidos', 'opgg',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventario_user_pass'), table_name='inventario')
    op.drop_index(op.f('ix_inventario_id'), table_name='inventario')
    op.alter_column('inventario', 'descripcion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('inventario', 'user_pass',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_config_precios_division'), table_name='config_precios')
    op.alter_column('config_precios', 'margen_perez',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('config_precios', 'precio_cliente',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_boosters_nombre'), table_name='boosters')
    op.drop_index(op.f('ix_boosters_id'), table_name='boosters')
    op.create_unique_constraint(op.f('boosters_nombre_key'), 'boosters', ['nombre'], postgresql_nulls_not_distinct=False)
    op.alter_column('boosters', 'discord_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('boosters', 'password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'1234'::text"))
    op.alter_column('boosters', 'binance',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('boosters', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('evento', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('detalles', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('logs_pkey'))
    )
    # ### end Alembic commands ###
